### PR TITLE
Create handlers for api [WIP]

### PR DESCRIPTION
**Pull request by yugoccp**
@Phani, created the handlers for API, but run into some passport.js error which couldn't get to a solution :(... Can you please take a look?

### CODE REVIEW

**Comment by pasupulaphani** [comment]
@yugoccp Is this completed?

**Comment by pasupulaphani** [comment]
@yugoccp @sbidolach 
Also, please consider '[wip]' or 'do not merge' to the title if the work doesn't need to be merged. It will be easier for people to merge or skip.

**Comment by sbidolach** [comment]
Ok my mistake, I was too rush. Sorry, Phani.

**Comment by pasupulaphani** [comment]
No need to say sorry. I was just mentioning it to avoid confusion :)

**Comment by yugoccp** [comment]
Sorry! It was in progress D:!
Would add [WIP] next time!

**Comment by pasupulaphani** [comment]
What was the issue @yugoccp 

Can you create a new branch and add comments at the breaking code and send me a PR, if you can't speak on Skype.

**Comment by yugoccp** [comment]
Ok, I'm creating branch

**Comment by yugoccp** [comment]
Created branch fixErrors with comments on code.

Breafly:
1. Session user are not coming attached to the request. Causing error by
accessing undefined attribute.
2. Error with "can't send headers after they are sent" at server.js:66
3. Couldn't switch account API to the new format. /login are called with
"next" method null.

**Pull request merged**
